export const types = {
    CREATE_USER: 'CREATE_USER',
    ADD_NAME: 'ADD_NAME',
    CLEAR_INPUT: 'CLEAR_INPUT',
    CREATE_NUMBER: 'CREATE_NUMBER',
    ADD_NUMBER: 'ADD_NUMBER',
    CLEAR_INPUT_NUMBER: 'CLEAR_INPUT_NUMBER',
}